Health☑️
wurstmeister/kafka-docker pull request #474
Opened 2019-03-28 17:29 UTC by timdorr

Fixes #167 

I swiped the script from @knordstrom and @Lukkie. The general gist is that it asks Zookeeper for the brokers it knows about and checks that it is in that list. So, a little better than just a port check with netcat.

If anyone has ideas for improvement, please let me know and I'll add it to this PR.

2019-03-29 11:41 UTC, sscaling commented
The response in my comment to this issues still applies -  [https://github.com/wurstmeister/kafka-docker/issues/167#issuecomment-377179871](https://github.com/wurstmeister/kafka-docker/issues/167#issuecomment-377179871)

Health checks don't really provide much use other than an a queryable label on the running container.

It'd be great to understand what real-world use-case this particular solution solves to know on whether to proceed or not.

As an aside - i'm not sure this is a great approach to health check, all it does is validate that the broker has registered and been assigned a znode - it has no real indication of whether Kafka is healthy or not, the only half decent way of doing so is via a successful query to the brokers. Even with that said, if your brokers are in a distinct network from your clients and communication is via an external port a health check from inside the broker network becomes misleading, i.e. it could appear healthy but be completely unusable.

2019-04-04 13:23 UTC, fvigotti commented
In my installation which may be slightly different but probably not so much..  the 
shell commands ( ie : zookeeper-shell.sh  ) use same env variables as kafka.. 
with the provided script there could be problems ie: if the pod is limited in memory to something less than 200% of the -Xmx or if the kafka is exporting JMX maybe would be usefull to reset/reimport from another name those variables 
```
KAFKA_HEAP_OPTS="-Xms200M -Xmx500M"
## avoid conflicts on jmx ports with kafka 
KAFKA_JMX_OPTS=""
JMX_PORT=""
```

2021-12-08 03:36 UTC, jayvdb requested changes

2021-12-08 03:36 UTC, jayvdb commented on healthcheck.sh
> +ids=( $r )
trailing whitespace on this line and the previous line

also fwiw, using "health☑️" as a branch name makes it difficult for others to use your branch.

2025-09-23 16:49 UTC, closed without merging